name: Metal access

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build
            package.json
            package-lock.json
          retention-days: 1
  deploy:
    name: Deploy project
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Debug files
        run: find . -maxdepth 3 | sort
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
      - name: Setup Rsync
        run: |
          sudo apt update
          sudo apt install rsync -y
      - name: Deploy to VPS
        run: |
          rsync -avz ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:${{ secrets.DEPLOY_PATH }}/build
          rsync -avz package.json package-lock.json ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:${{ secrets.DEPLOY_PATH }}/
      - name: Install production dependencies
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} \
            "cd ${{ secrets.DEPLOY_PATH }} && npm ci --omit=dev"
      - name: Restart service
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} \
            "source .bashrc && cd ${{ secrets.DEPLOY_PATH }} && pm2 restart ${{ vars.PROJECT_NAME }}"
